development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: app-dev
  pool: 5
  username: christopherperry
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: app-test
  pool: 5
  username: christopherperry
  password: